### PR TITLE
Add patch for connected event issue

### PR DESCRIPTION
**Pull request by kb0rg**
TODO:
- [x] debug and fix release notification not being sent (context [here](https://www.flowdock.com/app/cardforcoin/bifrost/threads/DGSlhr8H20sIQ8T17GJtLC_6Z41))

This PR adds the patch that @Shadowfiend made (and [opened a PR for](https://github.com/flowdock/hubot-flowdock/pull/109))  many months ago to our fork of the flowdock adapter

### CODE REVIEW

**Comment by kb0rg** [comment]
Currently testing heimdall with this branch, will mark WIP until we've seen how this plays out

**Comment by kb0rg** [comment]
@Shadowfiend if you prefer to close this out and open a new PR yourself, since this is your work anyway, go for it. 

Also, I don't think this really needs to wait for the PR referenced in the TODO after all

**Comment by Shadowfiend** [comment]
Missed this guy until just now---it's working, I think we can just merge. Any reason not to on your end?

**Review by Shadowfiend — APPROVED** [review]
Okay let's do the thing!

**Pull request merged**
